name: Manter Dashboard Ativo

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à 00 hr UTC
  workflow_dispatch: # Permite execução manual

jobs:
  ping:
      runs-on: ubuntu-latest

      steps:
        - name: Enviar requisição para manter o dashboard ativo
          run: |
            curl -X GET https://ecommerce-brazil-analytics.streamlit.app/ > /dev/null